# Generated by Django 2.1.5 on 2019-02-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300, unique=True)),
                ('pws', models.CharField(max_length=300, unique=True)),
                ('contact', models.CharField(max_length=300, unique=True)),
                ('address', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
