# Generated by Django 2.1.5 on 2019-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300, unique=True)),
                ('model', models.CharField(max_length=300, unique=True)),
                ('price', models.CharField(max_length=300, unique=True)),
                ('quantity', models.CharField(max_length=300, unique=True)),
                ('product_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
