# Generated by Django 2.1.5 on 2019-02-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtoCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=300)),
                ('productid', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
